# dsh-plugin-guide official-docs sync script.
# Purpose: sync the deepseek-harness checkout's official docs into references/official-docs/ (verbatim copy).
# Source is pinned to origin/master (HEAD fallback): untracked drafts and unpushed commits in the checkout never enter the KB.
# Output: references/official-docs/SNAPSHOT.md (source ref/SHA, sync time, file counts - the freshness authority for READMEs).
# Usage:  pwsh -File scripts/sync-official-docs.ps1 [-Checkout <path>] [-SkipGit]
# Verify: pwsh -File scripts/verify-kit.ps1 -Checkout <path>   # drift report KB vs checkout (tracked files only)
param(
  [string]$Checkout = 'D:\deepseek-harness',
  [switch]$SkipGit
)
$ErrorActionPreference = 'Stop'
$kit  = Split-Path $PSScriptRoot -Parent
$dest = Join-Path $kit 'references\official-docs'

if (-not (Test-Path $Checkout)) { Write-Error "checkout not found: $Checkout"; exit 1 }

$gitOk = $false
if (-not $SkipGit) {
  $gitOk = (& git -C $Checkout rev-parse --is-inside-work-tree 2>$null) -eq 'true'
}

$ref = 'filesystem'
$sha = ''
$pruned = 0
$mdCount = 0
$zhCount = 0

# Sync scope: docs/, root AGENTS.md, packages/AGENTS.md, examples/AGENTS.md, packages/README.md, vendor/README.md, website/docs.ts
$paths = @('docs', 'AGENTS.md', 'packages/AGENTS.md', 'examples/AGENTS.md', 'packages/README.md', 'vendor/README.md', 'website/docs.ts')

if ($gitOk) {
  # Prefer origin/master, fall back to HEAD - never the working tree (may contain untracked/unpushed content).
  if ((& git -C $Checkout rev-parse --verify -q origin/master 2>$null)) { $ref = 'origin/master' } else { $ref = 'HEAD' }
  $sha = (& git -C $Checkout rev-parse $ref).Trim()

  $tmp = Join-Path ([System.IO.Path]::GetTempPath()) ("dsh-official-docs-$sha.tar")
  & git -C $Checkout archive -o $tmp $ref -- $paths
  if ($LASTEXITCODE -ne 0) { Write-Error "git archive failed (ref=$ref)"; exit 1 }

  New-Item -ItemType Directory -Force -Path $dest | Out-Null
  & tar -xf $tmp -C $dest
  if ($LASTEXITCODE -ne 0) { Write-Error 'tar extraction failed'; Remove-Item $tmp -Force -ErrorAction SilentlyContinue; exit 1 }
  Remove-Item $tmp -Force

  # website/docs.ts keeps its in-repo filename in the archive; move it to the KB's flat name.
  if (Test-Path (Join-Path $dest 'website\docs.ts')) {
    Copy-Item (Join-Path $dest 'website\docs.ts') (Join-Path $dest 'website-docs.ts') -Force
    Remove-Item (Join-Path $dest 'website\docs.ts') -Force
    Remove-Item (Join-Path $dest 'website') -Force -Recurse -ErrorAction SilentlyContinue
  }

  # Prune docs/ files that no longer exist in the source ref (a verbatim copy does not keep upstream-deleted content).
  $tracked = New-Object System.Collections.Generic.HashSet[string]
  foreach ($t in (& git -C $Checkout ls-tree -r --name-only $ref -- docs)) { [void]$tracked.Add($t.Replace('\','/')) }
  $docsDir = Join-Path $dest 'docs'
  if (Test-Path $docsDir) {
    $docsRoot = (Resolve-Path $docsDir).Path
    Get-ChildItem -Recurse -File $docsDir | ForEach-Object {
      $rel = 'docs/' + $_.FullName.Substring($docsRoot.Length + 1).Replace('\','/')
      if (-not $tracked.Contains($rel)) { Remove-Item $_.FullName -Force; $pruned++ }
    }
  }
} else {
  Write-Output 'WARN: checkout is not a git repo (or -SkipGit) - copying the filesystem as-is; untracked files are not filtered and no pruning runs.'
  foreach ($p in $paths) {
    $srcFull = Join-Path $Checkout ($p -replace '/','\')
    if (-not (Test-Path $srcFull)) { Write-Output "SKIP(source missing): $p"; continue }
    $target = Join-Path $dest ($p -replace '/','\')
    $tdir = Split-Path $target -Parent
    if ($tdir -and -not (Test-Path $tdir)) { New-Item -ItemType Directory -Force -Path $tdir | Out-Null }
    Copy-Item $srcFull $target -Recurse -Force
  }
}

$mdCount = (Get-ChildItem -Recurse -File (Join-Path $dest 'docs') -Filter *.md).Count
$zhCount = (Get-ChildItem -Recurse -File (Join-Path $dest 'docs') -Filter *.zh.md).Count
$utc = (Get-Date).ToUniversalTime().ToString('yyyy-MM-ddTHH:mm:ssZ')
$L = @(
  '# official-docs snapshot (SNAPSHOT.md)',
  '',
  '> Generated by `scripts/sync-official-docs.ps1`. This file is the single authority for how `references/official-docs/` lines up with upstream deepseek-harness.',
  '> The "last verified" dates and commit SHAs in README/guide must cite this file; do not hand-edit them.',
  '',
  '| Item | Value |',
  '|---|---|',
  "| Source checkout | ``$Checkout`` |",
  "| Source ref | ``$ref`` |",
  "| Source commit | ``$sha`` |",
  "| Synced at (UTC) | $utc |",
  '| Scope | tracked files at the ref: `docs/`, root `AGENTS.md`, `packages/AGENTS.md`, `examples/AGENTS.md`, `packages/README.md`, `vendor/README.md`, `website/docs.ts` |',
  "| File counts | docs/: $mdCount md files ($zhCount .zh.md pairs) |",
  "| Pruned this run | $pruned docs/ files no longer in the source ref |",
  '',
  'Drift check: `pwsh -File scripts/verify-kit.ps1 -Checkout <checkout>` (tracked files only).'
)
Set-Content -Path (Join-Path $dest 'SNAPSHOT.md') -Value ($L -join "`r`n") -Encoding UTF8

Write-Output "DONE: ref=$ref sha=$sha pruned=$pruned -> $dest"
